sudo: required
services: 
  - docker

before_install:
  - docker build -t oneandwholly/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true oneandwholly/docker-react npm run test -- --coverage